'use client';
import {useState,type FormEvent} from 'react';
import {LogIn,UserPlus,ShieldCheck} from 'lucide-react';
import {onboardingRole} from '@/lib/onboarding';
import {Package,Truck,Users} from 'lucide-react';
import {api,type SessionUser} from '@/lib/api-client';
import {PanelTitle} from '../primitives';
export default function AuthPanel({onLogin}:{onLogin:(u:SessionUser)=>void}){
 const [path,setPath]=useState<'generator'|'collect'>('generator'),[acting,setActing]=useState<'collector'|'cooperative'|undefined>();
 const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(signup){const role=onboardingRole(path,acting);if(!role){setError('Escolha como você atua.');return;}d.role=role;}setBusy(true);setError('');try{const result=await api<{user:SessionUser}>('auth/'+(signup?'register':'login'),'POST',d);onLogin(result.user);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="form-layout"><section className="panel"><PanelTitle title={signup?'Crie sua conta':'Entre no ReciclaMapa'} subtitle="Seus dados acompanham sua conta entre dispositivos."/><form className="form-body" onSubmit={submit}><div className="form-grid">{signup&&<><label className="wide">Seu nome<input name="name" required maxLength={100} autoComplete="name"/></label><fieldset className="wide onboarding"><legend>O que você quer fazer?</legend><div className="onboarding-grid"><button type="button" aria-pressed={path==='generator'} onClick={()=>setPath('generator')}><Package/><b>Tenho materiais recicláveis</b><span>Quero disponibilizar materiais para coleta.</span></button><button type="button" aria-pressed={path==='collect'} onClick={()=>setPath('collect')}><Truck/><b>Quero coletar materiais</b><span>Quero encontrar materiais e organizar coletas.</span></button></div>{path==='collect'&&<fieldset><legend>Como você atua?</legend><div className="onboarding-grid"><button type="button" aria-pressed={acting==='collector'} onClick={()=>setActing('collector')}><Truck/><b>Catador independente</b></button><button type="button" aria-pressed={acting==='cooperative'} onClick={()=>setActing('cooperative')}><Users/><b>Cooperativa / associação</b></button></div></fieldset>}</fieldset></>}<label className="wide">E-mail<input name="email" type="email" autoComplete="email" maxLength={254} required/></label><label className="wide">Senha<input name="password" type="password" minLength={signup?12:1} maxLength={72} autoComplete={signup?'new-password':'current-password'} required/>{signup&&<small>Use pelo menos 12 caracteres. Não reutilize uma senha de outro serviço.</small>}</label>{signup&&<><label>Cidade<input name="city" required maxLength={100}/></label><label>Estado<input name="state" required maxLength={50}/></label><label className="wide">Bairro<input name="neighborhood" required maxLength={100}/></label></>}</div>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="form-actions"><button className="text-btn" type="button" onClick={()=>{setSignup(!signup);setError('');}}>{signup?'Já tenho uma conta':'Criar conta'}</button><button className="btn primary" disabled={busy}>{signup?<UserPlus size={17}/>:<LogIn size={17}/>} {busy?'Aguarde...':signup?'Criar conta':'Entrar'}</button></div></form></section><aside className="help-card"><ShieldCheck size={32}/><h2>Uma conta.<br/>Um ciclo completo.</h2><p>Geradores acompanham seus materiais. Cooperativas reservam, agendam e registram o peso realmente coletado.</p><p>A demonstração continua disponível separadamente. Localizações residenciais são aproximadas para pessoas não autorizadas.</p></aside></div>;
}
