'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api-client';
import {STORAGE_KEY,migrateState} from '@/lib/storage';
import {PanelTitle} from '../primitives';
type Archive={id:string;createdAt:string;payload:string};
export default function LegacyImport({onImported}:{onImported:()=>void}){
 const [payload,setPayload]=useState<unknown>(null),[archives,setArchives]=useState<Archive[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const old=migrateState(JSON.parse(raw));if(old.registered.points.length||old.registered.collections.length||Object.values(old.validation).some(v=>typeof v==='number'?v>0:typeof v==='string'&&v&&v!=='Não informado'))setPayload({registered:old.registered,validation:old.validation});}}catch{setError('Há dados antigos que precisam de revisão antes de importar. O original foi preservado.');}api<Archive[]>('import').then(setArchives).catch(e=>setError(e.message));},[]);
 async function importData(){setBusy(true);setError('');try{await api('import','POST',payload);setArchives(await api<Archive[]>('import'));localStorage.removeItem(STORAGE_KEY);localStorage.removeItem('reciclamapa-backup-before-v2');setPayload(null);onImported();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel section-gap"><PanelTitle title="Dados das etapas anteriores" subtitle="Migração dos registros deste navegador para sua conta."/>{payload?<div className="form-body"><p>Os registros próprios serão vinculados à sua conta. Histórico sem peso real e planos antigos ficam preservados como legado, sem gerar métricas comprovadas. Os totais antigos de validação não serão convertidos em entrevistas individuais.</p><label className="check-row"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> Confirmo que estes registros são meus e representam dados reais.</label><button className="btn primary" disabled={!confirm||busy} onClick={importData}>{busy?'Importando...':'Importar meus dados para o banco'}</button></div>:<p className="form-body">{archives.length?'Importação preservada no banco.':'Nenhum registro local pendente de migração.'}</p>}{error&&<p role="alert" className="error-banner">{error}</p>}{archives.map(a=><details className="form-body" key={a.id}><summary>Arquivo legado · {new Date(a.createdAt).toLocaleDateString('pt-BR')}</summary><p>Conteúdo original privado, preservado para consulta.</p><pre className="legacy-json">{JSON.stringify(JSON.parse(a.payload),null,2)}</pre></details>)}</section>;
}
