'use client';
import {useAccount} from './account-context';
import {api} from '@/lib/api-client';
import {useState,useEffect} from 'react';
import type {Collection} from '@/types';
import {num} from '@/lib/model';
import {FeatureGate} from './plans-page';
export default function OrganizationReports({collections,navigate,selectedPeriod='all'}:{collections:Collection[];navigate:(p:string)=>void;selectedPeriod?:string}){
 const {demo,access}=useAccount();
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[period,setPeriod]=useState('all');
 const [productivity,setProductivity]=useState<{stops:number;kgPerCompletedRoute:number}|null>(null);
 useEffect(()=>{if(demo||!access.features.productivity)return;const ctrl=new AbortController();api<{stops:number;kgPerCompletedRoute:number}>('reports/productivity?period='+selectedPeriod,'GET',undefined,ctrl.signal).then(setProductivity).catch(e=>{if(!ctrl.signal.aborted)setError(e.message);});return()=>ctrl.abort();},[demo,access.features.productivity,selectedPeriod,collections]);
 const completed=collections.filter(c=>c.completed!==false),demoStats={stops:collections.flatMap(c=>c.points).length,kgPerCompletedRoute:completed.length?completed.reduce((sum,c)=>sum+c.kg,0)/completed.length:0},stats=demo?demoStats:productivity;
 async function download(){setBusy(true);setError('');try{if(demo){const csv='Origem;Data;Coletado (kg)\r\n'+collections.map(c=>'Demonstração;'+c.date+';'+c.kg).join('\r\n'),url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='reciclamapa-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}const response=await fetch('/api/reports/export?period='+period,{credentials:'same-origin'});if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download='reciclamapa-organizacao.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="settings-stack section-gap"><FeatureGate feature="productivity" navigate={navigate}><section className="panel form-body"><h2>Produtividade da organização</h2>{stats?<p>{stats.stops} paradas registradas · {num(stats.kgPerCompletedRoute)} kg {demo?'demonstrativos':'reais'} por rota finalizada.</p>:<p role="status">Carregando produtividade…</p>}<small>Considera o período selecionado nos indicadores abaixo. Rotas ainda abertas não entram na média por rota.</small></section></FeatureGate><FeatureGate feature="exports" navigate={navigate}><section className="panel form-body"><h2>Relatório da organização</h2><p>Exportação CSV dos resultados autorizados, sem endereços privados ou dados de outras organizações.</p>{demo&&<p>Demonstração: exporta somente os resultados fictícios deste navegador.</p>}<label>Período da exportação<select disabled={demo} value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Todo o período</option><option value="today">Hoje</option><option value="7">7 dias</option><option value="30">30 dias</option></select></label><button className="btn light" onClick={download} disabled={busy}>{busy?'Preparando…':'Exportar CSV'}</button>{error&&<p role="alert" className="error-banner">{error}</p>}</section></FeatureGate></div>;
}
