'use client';
import {Check,LockKeyhole} from 'lucide-react';
import {FEATURES,PLANS,type Feature,type PlanId} from '@/lib/plans';
import {useAccount} from './account-context';
export function FeatureGate({feature,navigate,children}:{feature:Feature;navigate:(p:string)=>void;children:React.ReactNode}){
 const {access,loading,error,refresh}=useAccount();if(error)return <p className="error-banner" role="alert">Não foi possível consultar seu acesso. <button className="btn" onClick={()=>refresh().catch(()=>{})}>Tentar novamente</button></p>;if(loading)return <p role="status">Carregando acesso…</p>;
 if(access.features[feature])return children;
 const f=FEATURES[feature];return <section className="panel feature-gate"><LockKeyhole size={24}/><h2>{f.label}</h2><p>{f.ready?'Disponível no '+PLANS[f.plan].name:'Em desenvolvimento'}</p><button className="btn light" onClick={()=>navigate('plans')}>Comparar planos</button></section>;
}
export default function PlansPage(){
 const {access,demo,demoPlan,setDemoPlan,loading,error}=useAccount();
 return <div className="plans-page"><div className="notice"><p>O acesso básico permanece gratuito. Os planos Pro e Institucional são propostas comerciais, sem cobrança ou contratação ativa. O plano libera recursos; o perfil e as permissões continuam definindo quais dados você pode acessar.</p></div>{error&&<p className="error-banner" role="alert">{error}</p>}{loading?<p role="status">Consultando plano…</p>:<p>Plano {demo?'demonstrativo':'atual'}: <b>{PLANS[access.plan].name}</b> · {demo?'Somente dados fictícios':access.scope==='organization'?'Vinculado à sua organização':'Vinculado à sua conta'}</p>}{access.legacy&&<p className="notice">Seus acessos anteriores foram preservados. Nenhuma operação em andamento ou registro foi bloqueado. Uma mudança futura exige migração explícita.</p>}{demo&&<label className="demo-plan-select">Explorar plano na demonstração<select value={demoPlan} onChange={e=>setDemoPlan(e.target.value as PlanId)}>{Object.entries(PLANS).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select><small>Esta escolha não altera contas, planos ou permissões reais. O planejador da demo é ilustrativo e mantém uma rota; rotas paralelas são persistidas na operação real.</small></label>}<div className="plan-grid">{(Object.keys(PLANS) as PlanId[]).map(id=>{const p=PLANS[id];return <article className={'panel plan-card '+(access.plan===id?'current':'')} key={id}><span className="plan-tag">{access.plan===id?demo?'Em exploração':'Plano atual':id==='free'?'Acesso básico':'Proposta comercial'}</span><h2>{p.name}</h2><p>{p.audience}</p><strong className="plan-price">{p.price}</strong>{id!=='free'&&<p>Inclui tudo do {id==='pro'?'Gratuito':'Pro'}.</p>}<ul>{Object.values(FEATURES).filter(f=>f.plan===id).map(f=><li key={f.label}><Check size={16}/><span>{f.label}{!f.ready&&<small>Em desenvolvimento</small>}</span></li>)}</ul><p className="plan-note">{id==='free'?'As funções essenciais de coleta e seus próprios registros permanecem acessíveis.':'Contratação em breve'}</p></article>;})}</div><section className="panel"><h2 className="form-body">Comparação de funcionalidades</h2><div className="table-wrap"><table><thead><tr><th>Recurso</th>{Object.values(PLANS).map(p=><th key={p.name}>{p.name}</th>)}</tr></thead><tbody>{Object.entries(FEATURES).map(([id,f])=><tr key={id}><td>{f.label}</td>{(['free','pro','institutional'] as PlanId[]).map(p=><td key={p}>{({free:0,pro:1,institutional:2}[p]<{free:0,pro:1,institutional:2}[f.plan])?'—':f.ready?'Incluído':'Em desenvolvimento'}</td>)}</tr>)}</tbody></table></div></section></div>;
}
