'use client';
import {useEffect,useState} from 'react';
import {useAccount,type Account} from './account-context';
import {api,roleLabel} from '@/lib/api-client';
import {NOTIFICATION_CATEGORIES,type Preferences} from '@/lib/preferences';
import {FeatureGate} from './plans-page';
export default function SettingsPage({page,navigate}:{page:string;navigate:(p:string)=>void}){
 const {account,demo,demoRole,preferences,save,update,exit,loading,error:loadError,refresh}=useAccount(),[draft,setDraft]=useState<Preferences>(preferences),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[passwordChanged,setPasswordChanged]=useState(false);
 useEffect(()=>setDraft(preferences),[preferences]);
 async function run(action:()=>Promise<void>,success:string){setBusy(true);setError('');setMessage('');try{await action();setMessage(success);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(passwordChanged)return <section className="panel form-body"><h2>Senha alterada</h2><p role="status">Todas as sessões foram encerradas. Entre novamente com sua nova senha.</p><button className="btn primary" onClick={()=>exit().catch(e=>setError(e.message))}>Voltar para entrar</button>{error&&<p role="alert">{error}</p>}</section>;
 if(loading)return <p role="status">Carregando configurações…</p>;
 if(!demo&&!account)return <div className="error-banner" role="alert">{loadError||'Sessão indisponível.'}<button className="btn" onClick={()=>refresh().catch(()=>{})}>Tentar novamente</button></div>;
 return <div className="settings-stack">{error&&<p role="alert" className="error-banner">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}{demo&&<p className="notice">Perfil demonstrativo. Aparência e preferências ficam somente neste navegador. Dados pessoais e segurança exigem uma conta real.</p>}
 {page==='profile'?<section className="panel"><h2 className="form-body">Dados pessoais</h2><form className="form-body" key={account?.version??'demo'} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);run(async()=>{update(await api<Account>('account/profile','PATCH',{name:data.get('name'),phone:data.get('phone'),city:data.get('city'),state:data.get('state'),version:account!.version}));},'Perfil atualizado.');}}><div className="form-grid"><label>Nome<input name="name" required maxLength={100} disabled={demo||busy} defaultValue={account?.user.name??'Pessoa demonstrativa'} autoComplete="name"/></label><label>E-mail<input type="email" readOnly value={account?.user.email??'demo@exemplo.invalid'}/></label><label>Telefone (opcional)<input name="phone" maxLength={30} disabled={demo||busy} defaultValue={account?.profile?.phone??''} autoComplete="tel"/></label><label>Cidade<input name="city" required maxLength={100} disabled={demo||busy} defaultValue={account?.profile?.city??'Fortaleza'} autoComplete="address-level2"/></label><label>Estado<input name="state" required maxLength={50} disabled={demo||busy} defaultValue={account?.profile?.state??'CE'} autoComplete="address-level1"/></label><label>Perfil de atuação<input readOnly value={roleLabel[account?.user.role??demoRole]}/></label></div><p className="settings-help">A alteração de e-mail depende de verificação segura, ainda em desenvolvimento. A mudança de perfil também está em desenvolvimento para preservar vínculos e operações em andamento.</p>{!demo&&<button disabled={busy} className="btn primary">{busy?'Salvando…':'Salvar dados pessoais'}</button>}</form></section>:<>
 <form className="settings-stack" onSubmit={e=>{e.preventDefault();run(()=>save(draft),'Preferências salvas.');}}><section className="panel form-body"><h2>Aparência</h2><fieldset className="theme-options"><legend>Tema</legend>{[['light','Claro'],['dark','Escuro'],['system','Usar o tema do sistema']].map(([value,label])=><label key={value}><input type="radio" name="theme" value={value} checked={draft.theme===value} onChange={()=>setDraft(p=>({...p,theme:value as Preferences['theme']}))}/>{label}</label>)}</fieldset><label className="settings-check"><input type="checkbox" checked={draft.reduceMotion} onChange={e=>setDraft(p=>({...p,reduceMotion:e.target.checked}))}/>Reduzir animações</label><p className="settings-help">A aparência será aplicada ao salvar. A preferência do sistema também acompanha alterações do dispositivo.</p></section><section className="panel form-body"><h2>Notificações no site</h2><p className="settings-help">Escolha as categorias destacadas no sino. Todos os eventos continuam no histórico de notificações e na operação, inclusive avisos críticos. Não há envio por e-mail, WhatsApp ou push.</p>{Object.entries(NOTIFICATION_CATEGORIES).map(([key,label])=><label className="settings-check" key={key}><input type="checkbox" checked={draft.notifications[key as keyof Preferences['notifications']]} onChange={e=>setDraft(p=>({...p,notifications:{...p.notifications,[key]:e.target.checked}}))}/>{label}</label>)}</section><div><button className="btn primary" disabled={busy}>{busy?'Salvando…':'Salvar preferências'}</button></div></form>
 <section className="panel form-body"><h2>Segurança</h2>{demo?<p className="settings-help">Alteração de senha disponível somente em contas reais.</p>:<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(data.get('newPassword')!==data.get('repeat')){setError('As novas senhas não coincidem.');return;}run(async()=>{await api('account/password','POST',{currentPassword:data.get('currentPassword'),newPassword:data.get('newPassword')});setPasswordChanged(true);},'');}}><div className="form-grid section-gap"><label>Senha atual<input type="password" name="currentPassword" autoComplete="current-password" required maxLength={72}/></label><label>Nova senha<input type="password" name="newPassword" autoComplete="new-password" required minLength={12} maxLength={72}/></label><label>Confirmar nova senha<input type="password" name="repeat" autoComplete="new-password" required minLength={12} maxLength={72}/></label></div><p className="settings-help">Use pelo menos 12 caracteres. A alteração exige a senha atual e encerra todas as sessões.</p><button className="btn" disabled={busy}>Alterar senha e sair</button></form>}<button className="text-btn section-gap" disabled={busy} onClick={()=>run(exit,'')}>{demo?'Sair da demonstração':'Sair da conta'}</button></section>
 {['collector','cooperative'].includes(account?.user.role??demoRole)&&<section className="panel form-body"><h2>Minha organização</h2><p className="settings-help">Dados, base de coleta, materiais aceitos, capacidade e área de atuação usam o cadastro existente da cooperativa.</p><button className="btn light" onClick={()=>navigate('cooperative')}>Abrir minha organização</button></section>}
 {['collector','cooperative'].includes(account?.user.role??demoRole)&&<FeatureGate feature="team" navigate={navigate}><p>Equipe</p></FeatureGate>}
 </>}</div>;
}
