'use client';
import {useEffect,useRef,useState} from 'react';
import {Filter,Route,ArrowRight,Check,MapPin,Search,X} from 'lucide-react';
import {MATERIALS,TYPES,AVAILABILITIES,totalKg,num,type Point} from '@/lib/model';
import type {Coordinates,Cooperative} from '@/types';
import {calculateDistance,visibleLocation,hasDefinedLocation,inRadius} from '@/lib/geo';
import TerritoryMap from './territory-map';
import {Empty} from './primitives';
export function PointList({points,selected,onToggle,origin,onRelocate}:{points:Point[];selected:string[];onToggle:(id:string)=>void;origin?:Coordinates;onRelocate?:(p:Point)=>void}){return <div className="point-list">{points.map(p=><div className={`point-row ${selected.includes(p.id)?'chosen':''}`} key={p.id}><input type="checkbox" checked={selected.includes(p.id)} disabled={!hasDefinedLocation(p)} onChange={()=>onToggle(p.id)} aria-label={`Selecionar ${p.name}`}/><span className="point-material"><MapPin size={19}/></span><span className="point-main"><b>{p.name}</b><small>{p.material} · {p.region}</small><span className="point-meta">{p.availability} · {p.frequency}</span>{p.frequency!=='Única'&&<span className="recurring-label">↻ Fonte recorrente</span>}{origin&&hasDefinedLocation(p)&&<span className="distance-label">{num(calculateDistance(origin,visibleLocation(p)))} km · linha reta{p.type==='Residência'?' · aprox.':''}</span>}{!hasDefinedLocation(p)&&<button className="text-btn" onClick={()=>onRelocate?.(p)} disabled={!onRelocate}>Confirmar localização</button>}</span><span className="point-kg">{num(p.kg)}<small>kg</small></span></div>)}</div>}
export default function PointExplorer({points,selected,onToggle,onRoute,cooperative,onRelocate,remoteSearch,highlighted=[]}:{highlighted?:string[];points:Point[];selected:string[];onToggle:(id:string)=>void;onRoute:()=>void;cooperative?:Cooperative|null;onRelocate?:(p:Point)=>void;remoteSearch?:(query:string)=>void}){
  const [material,setMaterial]=useState(''),[region,setRegion]=useState(''),[minimum,setMinimum]=useState(''),[availability,setAvailability]=useState(''),[type,setType]=useState(''),[radius,setRadius]=useState('all'),[recurring,setRecurring]=useState(false),[serviceArea,setServiceArea]=useState(false),[acceptedOnly,setAcceptedOnly]=useState(false);
  const filterRef=useRef<HTMLDivElement>(null),[filtersOpen,setFiltersOpen]=useState(false);
  useEffect(()=>{if(!filtersOpen)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setFiltersOpen(false);if(e.key==='Tab'){const elements=filterRef.current?.querySelectorAll<HTMLElement>('button,select,input');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};filterRef.current?.querySelector<HTMLElement>('button')?.focus();window.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',close);};},[filtersOpen]);
  const effectiveRadius=serviceArea&&cooperative?cooperative.radiusKm:radius==='all'?undefined:Number(radius);
  const visible=points.filter(p=>(!material||p.material===material)&&(!region||p.region===region)&&p.kg>=Number(minimum)&&(!availability||p.availability===availability)&&(!type||p.type===type)&&(!recurring||p.frequency!=='Única')&&(!cooperative||effectiveRadius===undefined||inRadius(p,cooperative,effectiveRadius))&&(!acceptedOnly||!cooperative||cooperative.acceptedMaterials.includes(p.material)));
  useEffect(()=>{if(!remoteSearch)return;const q=new URLSearchParams();if(material)q.set('material',material);if(minimum)q.set('minimum',minimum);if(region)q.set('region',region);if(availability)q.set('availability',availability);if(type)q.set('type',type);if(recurring)q.set('recurring','true');if(effectiveRadius)q.set('radius',String(effectiveRadius));remoteSearch(q.toString());},[material,minimum,region,availability,type,recurring,effectiveRadius,remoteSearch]);
  function clear(){setMaterial('');setRegion('');setMinimum('');setAvailability('');setType('');setRadius('all');setRecurring(false);setServiceArea(false);setAcceptedOnly(false);}
  return <><button className="btn mobile-filter-trigger" onClick={()=>setFiltersOpen(true)}><Filter size={18}/> Filtros <span>{visible.length} pontos</span></button>{filtersOpen&&<button className="filter-backdrop" aria-label="Fechar filtros" onClick={()=>setFiltersOpen(false)}/>}<section className={`panel filter-panel ${filtersOpen?'filters-open':''}`} role={filtersOpen?'dialog':undefined} aria-modal={filtersOpen?true:undefined} aria-label="Filtros de resíduos" ref={filterRef}><div className="filter-title"><Filter size={18}/> Refinar território <span>{visible.length} pontos encontrados</span><button className="icon-btn filter-close" aria-label="Fechar filtros" onClick={()=>setFiltersOpen(false)}><X size={20}/></button></div><div className="filters"><label>Material<select value={material} onChange={e=>setMaterial(e.target.value)}><option value="">Todos os materiais</option>{MATERIALS.map(x=><option key={x}>{x}</option>)}</select></label><label>Quantidade mínima (kg)<input type="number" min="0" value={minimum} onChange={e=>setMinimum(e.target.value)} placeholder="0"/></label><label>Região<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">Todas as regiões</option>{[...new Set(points.map(p=>p.region))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Disponibilidade<select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="">Qualquer período</option>{AVAILABILITIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo de gerador<select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Distância da cooperativa<select value={radius} disabled={!cooperative||serviceArea} onChange={e=>setRadius(e.target.value)}><option value="all">Todos</option>{[5,10,15,20].map(k=><option key={k} value={k}>Até {k} km</option>)}</select></label></div><div className="filter-checks"><label className="check-row"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/> Somente recorrentes</label><label className="check-row"><input type="checkbox" checked={serviceArea} disabled={!cooperative} onChange={e=>setServiceArea(e.target.checked)}/> Área de atuação {cooperative?`(${cooperative.radiusKm} km)`:''}</label><label className="check-row"><input type="checkbox" checked={acceptedOnly} disabled={!cooperative} onChange={e=>setAcceptedOnly(e.target.checked)}/> Materiais aceitos</label></div>{!cooperative&&<p className="provider-note">Configure sua cooperativa para usar os filtros de raio e materiais aceitos.</p>}<div className="filter-actions"><button className="text-btn" onClick={clear}>Limpar filtros</button><button className="btn primary filter-close" onClick={()=>setFiltersOpen(false)}>Ver {visible.length} pontos</button></div></section>
  <div className="explorer-layout"><section className="panel large-map"><TerritoryMap highlighted={highlighted} points={visible} selected={selected} onToggle={onToggle} start={cooperative??undefined} radiusKm={effectiveRadius??cooperative?.radiusKm}/><div className="map-footnote">Localizações residenciais podem ser exibidas de forma aproximada para proteger a privacidade.</div><div className="material-legend"><span className="paper">Papel / papelão</span><span className="plastic">Plástico</span><span className="metal">Metal</span><span className="glass">Vidro</span><span className="electronics">Eletrônicos</span></div></section><section className="panel"><div className="panel-heading"><div><h2>Pontos disponíveis</h2><p>{num(totalKg(visible))} kg no filtro atual</p></div><Search size={18}/></div>{visible.length?<PointList points={visible} selected={selected} onToggle={onToggle} origin={cooperative??undefined} onRelocate={onRelocate}/>:<Empty title="Nenhum ponto neste filtro" text="Ajuste os filtros ou cadastre um resíduo."/>}</section></div>{selected.length>0&&<div className="selection-bar"><span><Check size={20}/><b>{selected.length} pontos</b> selecionados · {num(totalKg(points.filter(p=>selected.includes(p.id))))} kg (inclui pontos fora do filtro)</span><button className="btn primary" onClick={onRoute}><Route size={17}/> Planejar rota <ArrowRight size={16}/></button></div>}</>;
}
