'use client';
import {useState,type FormEvent} from 'react';
import {ArrowRight,MapPin,Save} from 'lucide-react';
import {MATERIALS,TYPES,AVAILABILITIES,FREQUENCIES,type Point,type Mode} from '@/lib/model';
import type { Coordinates } from '@/types';
import {hasDefinedLocation} from '@/lib/geo';
import {DataBadge,PanelTitle} from './primitives';
import LocationEditor,{blankAddress,type AddressDraft} from './Map/location-editor';
export default function Registration({mode,onSave,prefill,editing=false}:{mode:Mode;onSave:(p:Point)=>boolean|Promise<boolean>;prefill?:Point|null;editing?:boolean}){
  const [type,setType]=useState(prefill?.type??'Residência'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [position,setPosition]=useState<Coordinates|null>(prefill&&hasDefinedLocation(prefill)?{lat:prefill.lat,lng:prefill.lng}:null),[confirmed,setConfirmed]=useState(false);
  const [address,setAddress]=useState<AddressDraft>(prefill?{street:prefill.street??prefill.address,number:prefill.number??'',region:prefill.region,city:prefill.city??'',state:prefill.state??'',postcode:prefill.postcode??''}:{...blankAddress});
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);if(!confirmed||!position){setError('Defina e confirme a localização antes de publicar.');return;}
    const point:Point={id:editing&&prefill?prefill.id:crypto.randomUUID(),name:String(data.get('name')??'').trim(),type,material:String(data.get('material')),kg:Number(data.get('kg')),address:[address.street,address.number,address.region,address.city,address.state,address.postcode].filter(Boolean).join(', '),...address,availability:String(data.get('availability')),frequency:String(data.get('frequency')),...position,coordinateKind:mode==='simulated'?'demonstrative':'registered',locationConfirmed:true,source:mode,status:'available',createdAt:editing&&prefill?prefill.createdAt:new Date().toISOString()};
    if(!point.name||!address.street.trim()||!address.region.trim()||!address.city.trim()||!address.state.trim()||!Number.isFinite(point.kg)||point.kg<=0){setError('Confira os campos obrigatórios.');return;}setBusy(true);try{if(await onSave(point))setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <div className="form-layout"><section className="panel"><PanelTitle title={editing?'Confirmar localização do registro':prefill?'Registrar nova disponibilidade':'Um novo ponto de partida'} subtitle="Informe o material e confirme onde ele está disponível."/><form onSubmit={submit} className="form-body"><div className="form-grid"><label className="wide">Nome do gerador<input name="name" required maxLength={100} placeholder="Ex.: Mercado Central" defaultValue={prefill?.name}/></label><label>Tipo de gerador<select value={type} onChange={e=>{setType(e.target.value);setConfirmed(false);}}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Material<select name="material" defaultValue={prefill?.material}>{MATERIALS.map(t=><option key={t}>{t}</option>)}</select></label><label>Quantidade aproximada (kg)<input name="kg" type="number" min="0.1" max="1000000" step="0.1" required placeholder="Ex.: 20" defaultValue={editing?prefill?.kg:undefined}/></label><label>Disponibilidade<select name="availability" defaultValue={editing?prefill?.availability:'Hoje'}>{AVAILABILITIES.map(t=><option key={t}>{t}</option>)}</select></label><label>Recorrência<select name="frequency" defaultValue={prefill?.frequency??'Única'}>{FREQUENCIES.map(t=><option key={t}>{t}</option>)}</select></label></div><LocationEditor key={type} address={address} onAddress={setAddress} position={position} onPosition={setPosition} confirmed={confirmed} onConfirmed={setConfirmed} residential={type==='Residência'}/>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><DataBadge mode={mode}/><button className="btn primary" type="submit" disabled={busy||!confirmed||!position}><Save size={17}/> {busy?'Salvando...':editing?'Salvar alterações':'Salvar resíduo'}</button></div></form></section><aside className="help-card"><div className="help-icon"><MapPin size={28}/></div><h2>Um registro.<br/>Novas possibilidades.</h2><p>O material entra no mapa geográfico, nos indicadores e no planejamento de coleta.</p><ol><li>Informe o endereço</li><li>Confirme a localização</li><li>Planeje uma coleta</li></ol><div className="notice"><ArrowRight size={17}/><p>{mode==='simulated'?'Este registro será demonstrativo, mesmo com coordenadas geográficas.':'Os cadastros reais são salvos na sua conta. A confirmação de localização é feita por você.'}</p></div><p>Você pode continuar sem GPS ou busca de endereços: clique no mapa ou digite latitude e longitude.</p></aside></div>;
}
