'use client';
import {useEffect,useRef,useState} from 'react';
import {Route,Check,ArrowRight,Package,CalendarDays,Trash2,LoaderCircle,LocateFixed} from 'lucide-react';
import {activePoints,totalKg,num,materials,type Workspace,type RoutePlan} from '@/lib/model';
import {isCoordinate,hasDefinedLocation,visibleLocation} from '@/lib/geo';
import {compareRoutes,routeFingerprint} from '@/lib/routing';
import {locateUser} from '@/lib/geolocation';
import type {Coordinates} from '@/types';
import {Empty,DataBadge,PanelTitle} from './primitives';
import {PointList} from './point-explorer';
import TerritoryMap from './territory-map';
export default function RoutePlanner({workspace,selected,onToggle,onPlan,onComplete,onMap}:{workspace:Workspace;selected:string[];onToggle:(id:string)=>void;onPlan:(plan:RoutePlan|null)=>void;onComplete:(ids:string[],actualDistanceKm?:number)=>void;onMap:()=>void}){
  const coop=workspace.cooperative,plan=workspace.plan;
  const [confirm,setConfirm]=useState(false),[date,setDate]=useState(plan?.date??new Date().toLocaleDateString('en-CA'));
  const [startMode,setStartMode]=useState(plan?.comparison?'manual':coop?'cooperative':'first'),[endMode,setEndMode]=useState(plan?.comparison?.end?'manual':coop?'cooperative':'none');
  const [manualStart,setManualStart]=useState({lat:plan?.comparison?String(plan.comparison.start.lat):'',lng:plan?.comparison?String(plan.comparison.start.lng):''});
  const [manualEnd,setManualEnd]=useState({lat:plan?.comparison?.end?String(plan.comparison.end.lat):'',lng:plan?.comparison?.end?String(plan.comparison.end.lng):''});
  const [userLocation,setUserLocation]=useState<Coordinates|null>(null),[busy,setBusy]=useState(false),[locating,setLocating]=useState(false),[error,setError]=useState(''),[showOriginal,setShowOriginal]=useState(false),[actual,setActual]=useState('');
  const controller=useRef<AbortController|null>(null),requestId=useRef(0);
  useEffect(()=>()=>controller.current?.abort(),[]);
  const available=activePoints(workspace),points=selected.map(id=>available.find(p=>p.id===id)).filter(p=>!!p);
  const original=(plan?.originalIds??selected).map(id=>available.find(p=>p.id===id)).filter(p=>!!p);
  const manual=(value:{lat:string;lng:string})=>value.lat.trim()&&value.lng.trim()&&isCoordinate({lat:Number(value.lat),lng:Number(value.lng)})?{lat:Number(value.lat),lng:Number(value.lng)}:undefined;
  const start=startMode==='cooperative'?coop??undefined:startMode==='current'?userLocation??undefined:startMode==='first'?original[0]?visibleLocation(original[0]):undefined:manual(manualStart);
  const end=endMode==='cooperative'?coop??undefined:endMode==='manual'?manual(manualEnd):undefined;
  const fingerprint=start?routeFingerprint(original,start,end):'';
  const comparison=plan?.comparison?.fingerprint===fingerprint?plan.comparison:undefined;
  const ordered=(comparison?.suggestedIds??selected).map(id=>available.find(p=>p.id===id)).filter(p=>!!p);
  useEffect(()=>{requestId.current++;controller.current?.abort();setBusy(false);setConfirm(false);},[fingerprint]);
  function invalidate(){requestId.current++;controller.current?.abort();setBusy(false);setConfirm(false);if(plan?.comparison)onPlan({...plan,comparison:undefined,optimized:false});}
  async function locate(){invalidate();setLocating(true);setError('');try{const p=await locateUser();setUserLocation(p);setStartMode('current');}catch(e){setError((e as Error).message);}finally{setLocating(false);}}
  async function calculate(){if(!start){setError('Defina um ponto inicial válido ou configure sua cooperativa.');return;}const id=++requestId.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setError('');setConfirm(false);try{const result=await compareRoutes(original,start,end,abort.signal);if(id!==requestId.current)return;onPlan({ids:result.suggestedIds,originalIds:result.originalIds,date,optimized:true,comparison:result});}catch(e){if(!abort.signal.aborted)setError((e as Error).message);}finally{if(id===requestId.current)setBusy(false);}}
  const capacityWarning=coop&&totalKg(points)>coop.capacityKg,unsupported=coop?points.filter(p=>!coop.acceptedMaterials.includes(p.material)):[];
  return <><section className="panel route-config"><PanelTitle title="De onde sua coleta começa?" subtitle="A ordem de seleção será comparada com a sugestão por proximidade."/><div className="form-grid"><label>Ponto inicial<select value={startMode} onChange={e=>{invalidate();setStartMode(e.target.value);}}><option value="cooperative" disabled={!coop}>Cooperativa cadastrada</option><option value="current">Minha localização atual</option><option value="first">Primeiro ponto selecionado</option><option value="manual">Informar coordenadas</option></select></label><label>Destino final<select value={endMode} onChange={e=>{invalidate();setEndMode(e.target.value);}}><option value="cooperative" disabled={!coop}>Retornar à cooperativa</option><option value="none">Encerrar no último ponto</option><option value="manual">Outro destino por coordenadas</option></select></label>{startMode==='current'&&<button className="btn light" onClick={locate} disabled={locating}>{locating?<LoaderCircle size={17} className="spinning"/>:<LocateFixed size={17}/>} {locating?'Obtendo localização...':'Usar minha localização'}</button>}{startMode==='manual'&&<><label>Latitude inicial<input type="number" step="any" value={manualStart.lat} onChange={e=>{invalidate();setManualStart({...manualStart,lat:e.target.value});}}/></label><label>Longitude inicial<input type="number" step="any" value={manualStart.lng} onChange={e=>{invalidate();setManualStart({...manualStart,lng:e.target.value});}}/></label></>}{endMode==='manual'&&<><label>Latitude final<input type="number" step="any" value={manualEnd.lat} onChange={e=>{invalidate();setManualEnd({...manualEnd,lat:e.target.value});}}/></label><label>Longitude final<input type="number" step="any" value={manualEnd.lng} onChange={e=>{invalidate();setManualEnd({...manualEnd,lng:e.target.value});}}/></label></>}</div><p className="provider-note">Ao calcular, as coordenadas da rota são enviadas ao OSRM. Para residências, usamos somente posições aproximadas. Serviço público de demonstração, sem trânsito em tempo real.</p></section>
  <div className="route-summary"><div><Route size={27}/><span><b>{points.length}</b> paradas selecionadas</span></div><div><Package size={25}/><span><b>{num(totalKg(points))} kg</b> para coletar</span></div><label><CalendarDays size={19}/> Data da coleta<input aria-label="Data da coleta" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label></div>
  {(capacityWarning||unsupported.length>0)&&<div className="notice section-gap">{capacityWarning&&<span>O volume selecionado excede a capacidade cadastrada de {num(coop!.capacityKg)} kg. Divida a coleta em mais de uma rota.</span>}{unsupported.length>0&&<span>{unsupported.length} ponto(s) têm materiais não aceitos pela cooperativa.</span>}</div>}
  {error&&<div className="error-banner" role="alert">{error}</div>}
  <div className="route-layout"><section className="panel"><PanelTitle title="Seu roteiro de coleta" subtitle={comparison?'Ordem sugerida a partir de coordenadas e vias reais.':'Selecione os pontos e calcule o trajeto pelas ruas.'}/>{points.length?<><div className="route-stops">{ordered.map((p,i)=><div className="route-stop" key={p.id}><span>{i+1}</span><div><b>{p.name}</b><p>{p.material} · {p.region}{!hasDefinedLocation(p)&&' · Localização a confirmar'}</p></div><b>{num(p.kg)} kg</b><button className="icon-btn" aria-label={`Remover ${p.name} da rota`} disabled={busy} onClick={()=>onToggle(p.id)}><Trash2 size={16}/></button></div>)}</div><div className="route-actions"><button className="btn primary full" disabled={busy||!date||!start||(endMode!=='none'&&!end)} onClick={calculate}>{busy?<LoaderCircle className="spinning" size={17}/>:<Route size={17}/>} {busy?'Calculando rota...':comparison?'Recalcular rota real':'Calcular rota real'}</button><button className="btn full" disabled={busy||!date} onClick={()=>onPlan({ids:ordered.map(p=>p.id),originalIds:original.map(p=>p.id),date,optimized:!!comparison,comparison})}><CalendarDays size={17}/> Salvar programação</button><button className="btn light full" disabled={busy||!!capacityWarning||unsupported.length>0} onClick={()=>setConfirm(true)}><Check size={17}/> Concluir coleta</button>{!comparison&&<p className="provider-note">Uma coleta sem rota calculada registra o peso, mas não gera métricas de quilômetros evitados.</p>}{confirm&&<div className="confirmation" role="group" aria-label="Confirmar coleta"><b>Confirmar {num(totalKg(points))} kg coletados?</b><p>O histórico guardará o volume e a comparação viária, quando disponível.</p><label>Distância efetivamente percorrida (km, opcional)<input type="number" min="0" max="100000" step="0.1" value={actual} onChange={e=>setActual(e.target.value)} placeholder="Leitura do odômetro"/></label><p>Sem informação de percurso, a distância planejada permanece identificada como estimativa.</p><div><button className="btn primary" disabled={actual!==''&&(!Number.isFinite(Number(actual))||Number(actual)<0)} onClick={()=>{onComplete(points.map(p=>p.id),actual===''?undefined:Number(actual));setConfirm(false);}}>Confirmar coleta</button><button className="btn" onClick={()=>setConfirm(false)}>Cancelar</button></div></div>}</div></>:<Empty title="Sua próxima rota começa aqui" text="Selecione os pontos no mapa ou na lista abaixo." action={<button className="btn primary" onClick={onMap}>Selecionar no mapa <ArrowRight size={16}/></button>}/>}</section>
  <section className="panel large-map"><TerritoryMap points={points.length?points:available} selected={ordered.map(p=>p.id)} onToggle={busy?undefined:onToggle} route start={start} end={end} geometry={comparison?.suggested.geometry} originalGeometry={showOriginal?comparison?.original.geometry:undefined}/>{comparison&&<><div className="distance-comparison"><div><span>Antes · ordem de seleção</span><b>{num(comparison.original.distanceKm)} <small>km</small></b></div><ArrowRight size={20}/><div><span>Depois · rota sugerida</span><b>{num(comparison.suggested.distanceKm)} <small>km</small></b></div><DataBadge mode="road"/></div><div className="route-result"><b>Redução calculada: {num(Math.max(0,comparison.original.distanceKm-comparison.suggested.distanceKm))} km</b><p>{num(comparison.suggested.durationMinutes)} min estimados · {points.length} paradas · {num(totalKg(points))} kg</p><label className="check-row"><input type="checkbox" checked={showOriginal} onChange={e=>setShowOriginal(e.target.checked)}/> Comparar traçado original (cinza) com sugerido (verde)</label>{comparison.suggestedIds.join()===comparison.originalIds.join()&&<p>A ordem original foi mantida: a alternativa não reduziu a distância viária.</p>}</div></>}<p className="map-footnote">Trajeto por ruas calculado pelo OSRM, sobre dados OpenStreetMap. A heurística de proximidade não garante a rota ótima. {points.some(p=>p.type==='Residência')?'Paradas residenciais usam localizações aproximadas.':''} {points.some(p=>p.source==='simulated')?'Os geradores desta rota são demonstrativos.':''}</p><div className="material-tags">{materials(points).map(m=><span key={m.name}>{m.name} · {num(m.kg)} kg</span>)}</div></section></div>
  <section className="panel section-gap"><PanelTitle title="Adicionar pontos à rota" subtitle="Selecionar ou remover um ponto invalida o cálculo anterior."/>{available.length?<PointList points={available} selected={selected} onToggle={onToggle} origin={start}/>:<Empty title="Todos os materiais foram coletados" text="Cadastre novas disponibilidades para preparar outra rota."/>}</section></>;
}
