'use client';
import {useState,type FormEvent} from 'react';
import type {Point} from '@/types';
import {compatibleWindow,availabilityText} from '@/lib/collection-reliability';
import {num} from '@/lib/model';
export default function ActionForm({title,kind,points,onSubmit,onClose,busy,onRemove,reviewRequired=false}:{title:string;kind:string;points:Point[];onSubmit:(data:unknown)=>Promise<void>;onClose:()=>void;busy:boolean;onRemove?:(point:Point)=>Promise<void>;reviewRequired?:boolean}){
 const [error,setError]=useState(''),[date,setDate]=useState(new Date().toLocaleDateString('en-CA')),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const incompatible=kind==='schedule'&&start&&end?points.filter(p=>!compatibleWindow(p.pickupWindows,date,`${start}-${end}`)):[];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setError('');const body=kind==='schedule'?{date:form.get('date'),timeWindow:`${start}-${end}`,note:form.get('note'),review:form.get('review')==='on'}:kind==='collect'?{date:form.get('date'),items:points.map(p=>({id:p.id,actualWeight:Number(form.get(p.id))})),...(form.get('distance')?{distanceKm:Number(form.get('distance'))}:{})}:{};try{await onSubmit(body);}catch(e){setError((e as Error).message);}}
 return <section className="panel action-panel" aria-label={title}><form className="form-body" onSubmit={submit}><h2>{title}</h2>{kind==='cancel'?<p>A retirada deste material preserva o histórico, as outras paradas e as reservas. A organização responsável será avisada para revisar o planejamento. Ao cancelar uma rota inteira, suas reservas sem resultado serão liberadas.</p>:<div className="form-grid"><label>Data<input name="date" type="date" required value={date} onChange={e=>setDate(e.target.value)} min={kind==='schedule'?new Date().toLocaleDateString('en-CA'):undefined} max={kind==='collect'?new Date().toLocaleDateString('en-CA'):undefined}/></label>{kind==='schedule'?<><label>Início da janela<input type="time" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fim da janela<input type="time" required value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label><div className="wide"><p>Verificamos a faixa escolhida para todas as paradas. Não estimamos horários de chegada.</p>{points.map(p=><p className={incompatible.some(q=>q.id===p.id)?'error-banner':'pickup-info'} key={p.id}>{p.name}: {availabilityText(p.pickupWindows)}{incompatible.some(q=>q.id===p.id)?' · INCOMPATÍVEL':''}{incompatible.some(q=>q.id===p.id)&&onRemove&&<button className="btn" type="button" disabled={busy||points.length<=1} onClick={()=>onRemove(p).catch(e=>setError((e as Error).message))}>Retirar parada e liberar reserva</button>}</p>)}</div><label className="check-row wide"><input type="checkbox" name="review" required={reviewRequired||points.some(p=>p.planningReview)}/>Revisei os materiais e confirmo o planejamento atualizado.</label><label className="wide">Observação<textarea name="note" maxLength={500}/></label></>:<>{points.map(p=><label key={p.id}>{p.name} · {p.material}<small>Estimado: {num(p.kg)} kg</small><input aria-label={`Peso real de ${p.name}`} name={p.id} type="number" step="0.1" min="0.1" max="1000000" placeholder="Peso realmente coletado (kg)" required/></label>)}<label>Distância percorrida (km, opcional)<input name="distance" type="number" min="0" max="100000" step="0.1" placeholder="Leitura do odômetro"/></label><p>Somente os pesos reais informados entram no impacto. A distância planejada não substitui o percurso realizado.</p></>}</div>}{error&&<p role="alert" className="error-banner">{error}</p>}<div className="form-actions"><button className="btn" type="button" onClick={onClose} disabled={busy}>Voltar</button><button className="btn primary" disabled={busy||incompatible.length>0}>{busy?'Salvando...':'Confirmar'}</button></div></form></section>;
}
