'use client';
import {useState,type FormEvent} from 'react';
import type {Point} from '@/types';
import {num} from '@/lib/model';
export default function ActionForm({title,kind,points,onSubmit,onClose,busy}:{title:string;kind:string;points:Point[];onSubmit:(data:unknown)=>Promise<void>;onClose:()=>void;busy:boolean}){
 const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setError('');const body=kind==='schedule'?{date:form.get('date'),timeWindow:form.get('timeWindow'),note:form.get('note')}:kind==='collect'?{date:form.get('date'),items:points.map(p=>({id:p.id,actualWeight:Number(form.get(p.id))})),...(form.get('distance')?{distanceKm:Number(form.get('distance'))}:{})}:{};try{await onSubmit(body);}catch(e){setError((e as Error).message);}}
 return <section className="panel action-panel" aria-label={title}><form className="form-body" onSubmit={submit}><h2>{title}</h2>{kind==='cancel'?<p>O registro será cancelado, mantendo o histórico. Se estiver em uma rota aberta, a rota também será cancelada e os outros materiais serão liberados.</p>:<div className="form-grid"><label>Data<input name="date" type="date" required defaultValue={new Date().toLocaleDateString('en-CA')} min={kind==='schedule'?new Date().toLocaleDateString('en-CA'):undefined} max={kind==='collect'?new Date().toLocaleDateString('en-CA'):undefined}/></label>{kind==='schedule'?<><label>Horário aproximado<input name="timeWindow" required maxLength={80} placeholder="14h–16h"/></label><label className="wide">Observação<textarea name="note" maxLength={500}/></label></>:<>{points.map(p=><label key={p.id}>{p.name} · {p.material}<small>Estimado: {num(p.kg)} kg</small><input aria-label={`Peso real de ${p.name}`} name={p.id} type="number" step="0.1" min="0.1" max="1000000" placeholder="Peso realmente coletado (kg)" required/></label>)}<label>Distância percorrida (km, opcional)<input name="distance" type="number" min="0" max="100000" step="0.1" placeholder="Leitura do odômetro"/></label><p>Somente os pesos reais informados entram no impacto. A distância planejada não substitui o percurso realizado.</p></>}</div>}{error&&<p role="alert" className="error-banner">{error}</p>}<div className="form-actions"><button className="btn" type="button" onClick={onClose} disabled={busy}>Voltar</button><button className="btn primary" disabled={busy}>{busy?'Salvando...':'Confirmar'}</button></div></form></section>;
}
