'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Package,MapPin,Recycle,ClipboardCheck,LogOut,RefreshCw} from 'lucide-react';
import {api,wastePayload,roleLabel,type SessionUser} from '@/lib/api-client';
import type {Point,Cooperative,Collection} from '@/types';
import {totalKg,num} from '@/lib/model';
import {Stats,PanelTitle,Empty} from '../primitives';
import AuthPanel from '../Account/auth-panel';
import LegacyImport from '../Account/legacy-import';
import Registration from '../registration';
import PointExplorer from '../point-explorer';
import CooperativeSettings from '../Cooperative/settings';
import {Concentration,Impact} from '../analytics';
import WasteCards from './waste-cards';
import RoutesPanel,{type SavedRoute} from './routes-panel';
import ActionForm from './action-form';
import ValidationPanel from './validation-panel';
import AdminPanel from './admin-panel';
type Recurrence={name:string;material:string;region:string;frequency:string;samples:number;average:number;min:number;max:number;trend:number|null;records:{date:string;kg:number;status:string}[];point:Point};
export default function LiveWorkspace({page,navigate}:{page:string;navigate:(page:string)=>void}){
 const [user,setUser]=useState<SessionUser|null>(null),[sessionLoading,setSessionLoading]=useState(true),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [points,setPoints]=useState<Point[]>([]),[cooperative,setCooperative]=useState<Cooperative|null>(null),[routes,setRoutes]=useState<SavedRoute[]>([]),[collections,setCollections]=useState<Collection[]>([]),[history,setHistory]=useState<Recurrence[]>([]),[selected,setSelected]=useState<string[]>([]),[editing,setEditing]=useState<Point|null>(null),[repeat,setRepeat]=useState(false),[period,setPeriod]=useState('all'),[action,setAction]=useState<{point:Point;kind:string}|null>(null),[filters,setFilters]=useState(''),[total,setTotal]=useState(0);
 const version=useRef(0),query=useRef(filters);query.current=filters;
 useEffect(()=>{const c=new AbortController();api<{user:SessionUser|null}>('auth/session','GET',undefined,c.signal).then(r=>setUser(r.user)).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setSessionLoading(false);});return()=>c.abort();},[]);
 const refresh=useCallback(async()=>{if(!user)return;const v=++version.current;setLoading(true);try{const c=await api<Cooperative|null>('cooperatives?mine=true');const [w,i,r,h]=await Promise.all([api<{points:Point[];total:number}>('waste?limit=500'+(query.current?'&'+query.current:'')),user.role==='generator'||user.role==='admin'||c?api<{collections:Collection[]}>('impact?period='+period):Promise.resolve({collections:[]}),c?api<SavedRoute[]>('routes'):Promise.resolve([]),user.role==='generator'||user.role==='admin'||c?api<Recurrence[]>('history'):Promise.resolve([])]);if(v!==version.current)return;setCooperative(c);setPoints(w.points);setTotal(w.total);setCollections(i.collections);setRoutes(r);setHistory(h);setError('');}catch(e){if(v===version.current)setError((e as Error).message);throw e;}finally{if(v===version.current)setLoading(false);}},[user,period]);
 useEffect(()=>{refresh().catch(()=>{});const focus=()=>refresh().catch(()=>{});window.addEventListener('focus',focus);const timer=setInterval(()=>{if(document.visibilityState==='visible')focus();},30000);return()=>{version.current++;window.removeEventListener('focus',focus);clearInterval(timer);};},[refresh]);
 useEffect(()=>{setAction(null);setFilters('');query.current='';if(page!=='register'){setEditing(null);setRepeat(false);}refresh().catch(()=>{});},[page]);
 async function mutate(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
 function edit(p:Point){setEditing(p);setRepeat(false);navigate('register');}
 const operator=!!user&&['cooperative','collector'].includes(user.role),own=points.filter(p=>p.ownerId===user?.id),available=points.filter(p=>p.status==='available'),operational=points.filter(p=>['available','reserved','scheduled'].includes(p.status)),cards=page==='mine'||user?.role==='generator'&&page==='overview'?own:operational;
 async function pointAction(p:Point,kind:string){if(kind==='reserve')await mutate(async()=>{await api('waste/'+p.id+'/reserve','POST',{});setNotice('Material reservado para sua cooperativa.');}).catch(()=>{});else setAction({point:p,kind});}
 function select(pointId:string){setSelected(ids=>ids.includes(pointId)?ids.filter(x=>x!==pointId):[...ids,pointId]);}
 const useRemoteFilters=useCallback((q:string)=>{query.current=q;setFilters(q);},[]);
 useEffect(()=>{if(!user)return;const timer=setTimeout(()=>refresh().catch(()=>{}),350);return()=>clearTimeout(timer);},[filters]);
 if(sessionLoading)return <div className="data-skeleton" role="status">Carregando sua sessão...</div>;
 if(!user)return <>{error&&<p className="error-banner" role="alert">{error}</p>}<AuthPanel onLogin={u=>{setUser(u);setError('');}}/></>;
 return <><div className="account-bar"><div><b>{user.name}</b><span>{roleLabel[user.role]} · Dados salvos no banco</span></div><div><button className="btn light" onClick={()=>navigate('mine')}>Meus resíduos</button><button className="icon-btn" aria-label="Atualizar dados" disabled={loading||busy} onClick={()=>refresh().catch(()=>{})}><RefreshCw size={18}/></button><button className="btn" onClick={async()=>{try{await api('auth/logout','POST',{});version.current++;setUser(null);setPoints([]);setCollections([]);setSelected([]);setEditing(null);}catch(e){setError((e as Error).message);}}}><LogOut size={16}/> Sair</button></div></div>{error&&<div role="alert" className="error-banner">{error}</div>}{notice&&<p role="status" className="notice">{notice}<button className="text-btn" onClick={()=>setNotice('')}>Fechar</button></p>}{loading&&<div className="loading-line" role="status">Carregando materiais e histórico...</div>}
 {(page==='overview'||page==='mine')&&<><Stats items={[{title:operator?'Materiais disponíveis':'Meus resíduos',value:totalKg(operator?available:own.filter(p=>p.status==='available')),unit:'kg',icon:Package,desc:'Quantidade estimada cadastrada'},{title:'Pontos disponíveis',value:operator?available.length:own.filter(p=>p.status==='available').length,unit:'pontos',icon:MapPin,desc:'No filtro atual'},{title:'Peso real coletado',value:collections.reduce((s,c)=>s+c.kg,0),unit:'kg',icon:Recycle,desc:'Conforme registro da coleta'},{title:'Coletas concluídas',value:collections.length,unit:'coletas',icon:ClipboardCheck,desc:'Persistidas no banco'}]}/><section className="panel"><PanelTitle title={user.role==='generator'||page==='mine'?'Meus resíduos':'Operação da cooperativa'} subtitle="Acompanhe a disponibilidade, o agendamento e o resultado." action={<button className="btn primary" onClick={()=>navigate(user.role==='generator'?'register':'cooperative')}>{user.role==='generator'?'Cadastrar novo resíduo':'Abrir cooperativa'}</button>}/></section><WasteCards points={cards} user={user} cooperativeId={cooperative?.id} busy={busy} onEdit={edit} onAction={pointAction}/><LegacyImport onImported={()=>{setNotice('Dados importados. Registros antigos sem pesagem continuam identificados como legado.');refresh().catch(()=>{});}}/></>}
 {page==='register'&&(user.role==='generator'||user.role==='admin'?<Registration key={editing?.id??'new'} mode="registered" editing={!!editing&&!repeat} prefill={editing} onSave={async p=>{await mutate(async()=>{await api(editing&&!repeat?'waste/'+editing.id:'waste',editing&&!repeat?'PATCH':'POST',wastePayload(p));});setNotice('Resíduo salvo no banco.');setEditing(null);navigate('mine');return true;}}/>:<section className="panel"><Empty title="Cadastro destinado ao gerador" text="Seu perfil opera reservas e coletas. Os geradores cadastram os materiais em suas próprias contas."/></section>)}
 {page==='map'&&<><PointExplorer points={operational} selected={selected} onToggle={operator?select:()=>setNotice('Entre com um perfil de cooperativa ou coletor para reservar materiais.')} onRoute={()=>navigate('routes')} cooperative={cooperative} onRelocate={p=>{if(p.ownerId===user.id)edit(p);}} remoteSearch={useRemoteFilters}/><p className="provider-note">{points.length} de {total} registros retornados. A pesquisa e o filtro de raio são processados no servidor.</p><WasteCards points={operational} user={user} cooperativeId={cooperative?.id} busy={busy} onEdit={edit} onAction={pointAction}/></>}
 {page==='concentration'&&<Concentration points={available} onSelect={ids=>{if(!operator){setNotice('O planejamento é destinado às cooperativas e coletores.');return;}setSelected(ids);navigate('routes');}}/>}
 {page==='routes'&&(operator?<RoutesPanel points={points} selected={selected} cooperative={cooperative} routes={routes} onRefresh={refresh} onSelect={setSelected}/>:<section className="panel"><Empty title="Rotas da cooperativa" text="O perfil de gerador acompanha os agendamentos em Meus resíduos."/></section>)}
 {page==='cooperative'&&(operator?<><CooperativeSettings key={cooperative?.id??'new'} persistent value={cooperative} mode="registered" onSave={async c=>{await mutate(async()=>{await api('cooperatives','POST',{name:c.name,address:c.address,lat:c.lat,lng:c.lng,city:c.city,state:c.state,radiusKm:c.radiusKm,capacityKg:c.capacityKg,acceptedMaterials:c.acceptedMaterials});});setNotice('Cooperativa salva no banco.');}}/><div className="stats section-gap">{[['Coletas programadas',routes.filter(r=>r.status==='scheduled').length],['Rotas abertas',routes.filter(r=>['draft','scheduled','in_progress'].includes(r.status)).length],['Peso real coletado',num(collections.reduce((s,c)=>s+c.kg,0))+' kg']].map(([label,value])=><article className="stat" key={label}><div className="stat-label">{label}</div><div className="stat-value">{value}</div></article>)}</div><h2 className="section-gap">Materiais no território</h2><PointExplorer points={operational} selected={selected} onToggle={select} onRoute={()=>navigate('routes')} cooperative={cooperative} remoteSearch={useRemoteFilters}/><WasteCards points={operational} user={user} cooperativeId={cooperative?.id} busy={busy} onEdit={edit} onAction={pointAction}/></>:<section className="panel"><Empty title="Painel operacional" text="Disponível para perfis de cooperativa e coletor."/></section>)}
 {page==='impact'&&<><div className="period-filter"><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Hoje</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="all">Todo período</option></select></label><p>Resultados do banco, calculados a partir do peso realmente coletado. Registros legados sem pesagem ficam fora destes indicadores.</p></div><Impact workspace={{points,collections,plan:null,cooperative}}/></>}
 {page==='history'&&<><section className="panel"><PanelTitle title="Histórico de geração" subtitle="Cada novo lote é um registro. Estimativas dependem do histórico cadastrado."/></section>{history.length?history.map((h,i)=><article key={i} className="panel form-body section-gap"><h3>{h.name} · {h.material}</h3><p>{h.frequency} · {h.region} · {h.samples} registros</p><h3>Média {h.frequency==='Semanal'?'semanal':'por ciclo'}: {num(h.average)} kg</h3><p>Próxima geração prevista: {num(h.min)}–{num(h.max)} kg. Estimativa baseada em histórico.</p><p>{h.trend===null?'Ainda não há registros suficientes para tendência.':`Variação entre os dois últimos registros: ${h.trend>0?'+':''}${num(h.trend)} kg.`}</p><details><summary>Ver registros</summary>{h.records.map((r,j)=><p key={j}>{new Date(r.date).toLocaleDateString('pt-BR')} · {num(r.kg)} kg · {r.status}</p>)}</details>{user.role==='generator'&&<button className="btn light" onClick={()=>{setEditing(h.point);setRepeat(true);navigate('register');}}>Registrar novo lote</button>}</article>):<section className="panel"><Empty title="Sem fontes recorrentes cadastradas" text="Cadastre uma frequência para construir o histórico."/></section>}</>}
 {page==='validation'&&(user.role==='admin'?<ValidationPanel/>:<section className="panel"><Empty title="Validação protegida" text="Somente administradores podem consultar e registrar entrevistas."/></section>)}
 {page==='admin'&&(user.role==='admin'?<><AdminPanel/><h2 className="section-gap">Moderação de resíduos</h2><WasteCards points={points} user={user} cooperativeId={cooperative?.id} busy={busy} onEdit={edit} onAction={pointAction}/></>:<section className="panel"><Empty title="Acesso restrito" text="Seu perfil não tem acesso à gestão."/></section>)}
 {action&&<ActionForm key={action.point.id+action.kind} title={action.kind==='cancel'?'Cancelar resíduo':action.kind==='schedule'?'Agendar coleta':'Registrar coleta realizada'} kind={action.kind} points={[action.point]} busy={busy} onClose={()=>setAction(null)} onSubmit={async data=>{await mutate(async()=>{await api('waste/'+action.point.id+(action.kind==='cancel'?'':'/'+action.kind),action.kind==='cancel'?'DELETE':'POST',data);setNotice('Registro atualizado no banco.');});setAction(null);}}/>}</>;
}
