'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {api} from '@/lib/api-client';
import {PanelTitle,Empty} from '../primitives';
type Interview={id:string;intervieweeType:string;city:string;mainProblem:string;currentSolution:string;difficulty:string;wouldUse:string;notes:string;createdAt:string};
type Report={total:number;byType:Record<string,number>;wouldUsePercent:number|null;interviews:Interview[]};
export default function ValidationPanel(){
 const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>api<Report>('validation').then(setReport);useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{await api('validation','POST',Object.fromEntries(new FormData(form)));form.reset();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <>{error&&<p className="error-banner" role="alert">{error}</p>}{!report?<p role="status">Carregando entrevistas...</p>:<><div className="stats">{[['Entrevistas realizadas',report.total],['Catadores',report.byType.collector],['Cooperativas',report.byType.cooperative],['Comércios',report.byType.business],['Moradores',report.byType.resident],['Usariam a solução',report.wouldUsePercent===null?'—':report.wouldUsePercent.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%']].map(([label,value])=><article className="stat" key={label}><div className="stat-label">{label}</div><div className="stat-value">{value}</div></article>)}</div>{!report.total&&<section className="panel"><Empty title="Ainda não há dados de validação." text="Registre somente entrevistas realmente realizadas."/></section>}<section className="panel section-gap"><PanelTitle title="Registrar entrevista realizada" subtitle="Uma ficha por entrevista. Não é necessário identificar a pessoa."/><form onSubmit={save} className="form-body"><div className="form-grid"><label>Perfil entrevistado<select name="intervieweeType"><option value="collector">Catador</option><option value="cooperative">Cooperativa</option><option value="business">Comércio</option><option value="resident">Morador</option></select></label><label>Cidade<input name="city" required maxLength={100}/></label><label className="wide">Principal problema relatado<textarea name="mainProblem" required maxLength={1000}/></label><label className="wide">Solução atual<textarea name="currentSolution" required maxLength={1000}/></label><label className="wide">Dificuldade<textarea name="difficulty" required maxLength={1000}/></label><label>Usaria a solução?<select name="wouldUse"><option value="unsure">Não sabe</option><option value="yes">Sim</option><option value="no">Não</option></select></label><label className="wide">Observações<textarea name="notes" maxLength={2000}/></label></div><button className="btn primary" disabled={busy}>{busy?'Salvando...':'Salvar entrevista'}</button></form></section><section className="panel section-gap"><PanelTitle title="Problemas e relatos cadastrados"/>{report.interviews.map(i=><article className="form-body interview-record" key={i.id}><h3>{i.city} · {new Date(i.createdAt).toLocaleDateString('pt-BR')}</h3><p><b>Problema:</b> {i.mainProblem}</p><p><b>Solução atual:</b> {i.currentSolution}</p><p><b>Dificuldade:</b> {i.difficulty}</p><p>{i.notes}</p></article>)}</section></>}</>;
}
