'use client';
import type {Point} from '@/types';
import StatusTimeline from './status-timeline';
import {num} from '@/lib/model';
import {statusLabel,type SessionUser} from '@/lib/api-client';
import {Empty} from '../primitives';
export default function WasteCards({points,user,cooperativeId,onAction,onEdit,busy}:{points:Point[];user:SessionUser;cooperativeId?:string;onAction:(p:Point,action:string)=>void;onEdit:(p:Point)=>void;busy:boolean}){
 return <div className="operation-cards">{points.length?points.map(p=><article className="panel operation-card" key={p.id}><div className="operation-card-heading"><h3>{p.name}</h3><span className={`status-badge status-${p.status}`}>{statusLabel[p.status]}</span></div><StatusTimeline status={p.status} inProgress={p.inProgress}/><p><b>{p.material} · {num(p.kg)} kg estimados</b></p><p>{p.region} · {p.city} · {p.frequency}</p><small>Cadastrado em {new Date(p.createdAt).toLocaleDateString('pt-BR')}</small>{p.scheduledDate&&<div className="notice"><span>Coleta agendada: {p.scheduledDate.split('-').reverse().join('/')} · {p.timeWindow}<br/>{p.scheduleNote}</span></div>}{!p.locationConfirmed&&<p className="notice">Confirme a localização antes de disponibilizar este registro.</p>}<div className="operation-actions">{p.ownerId===user.id&&p.status==='available'&&<button className="btn light" disabled={busy} onClick={()=>onEdit(p)}>Editar resíduo</button>}{(p.ownerId===user.id||user.role==='admin')&&['available','reserved','scheduled'].includes(p.status)&&<button className="btn" disabled={busy} onClick={()=>onAction(p,'cancel')}>Cancelar resíduo</button>}{['cooperative','collector'].includes(user.role)&&p.status==='available'&&p.locationConfirmed&&<button className="btn primary" disabled={busy||!cooperativeId} onClick={()=>onAction(p,'reserve')}>Reservar para coleta</button>}{p.reservedBy===cooperativeId&&cooperativeId&&['reserved','scheduled'].includes(p.status)&&<><p>Reservado por sua cooperativa.</p><button className="btn" disabled={busy} onClick={()=>onAction(p,'release')}>Cancelar reserva</button><button className="btn light" disabled={busy} onClick={()=>onAction(p,'schedule')}>Agendar coleta</button>{p.status==='scheduled'&&<button className="btn primary" disabled={busy} onClick={()=>onAction(p,'collect')}>Registrar peso real</button>}</>}</div></article>):<section className="panel"><Empty title="Nenhum material nesta seleção" text="Cadastre um resíduo ou ajuste os filtros."/></section>}</div>;
}
