import { sqliteTable, text, real, integer, uniqueIndex, index, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
const timestamps = () => ({createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const users=sqliteTable('users',{
 id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),passwordHash:text('password_hash').notNull(),
 role:text('role',{enum:['generator','collector','cooperative','admin']}).notNull(),...timestamps()
});
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),userId:text('user_id').notNull().unique().references(()=>users.id),phone:text('phone'),city:text('city').notNull(),state:text('state').notNull(),neighborhood:text('neighborhood').notNull(),profileType:text('profile_type').notNull(),createdAt:text('created_at').notNull()});
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expiresAt:integer('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('sessions_user_idx').on(t.userId)]);
export const cooperatives=sqliteTable('cooperatives',{
 id:text('id').primaryKey(),ownerUserId:text('owner_user_id').notNull().unique().references(()=>users.id),name:text('name').notNull(),description:text('description').notNull().default(''),address:text('address').notNull(),lat:real('latitude').notNull(),lng:real('longitude').notNull(),city:text('city').notNull(),state:text('state').notNull(),radiusKm:real('service_radius_km').notNull(),minimumCollectionKg:real('minimum_collection_kg').notNull().default(0),capacityKg:real('daily_capacity_kg').notNull(),active:integer('active',{mode:'boolean'}).notNull().default(true),...timestamps()
},t=>[check('cooperative_positive',sql`${t.radiusKm}>0 AND ${t.capacityKg}>0`)]);
export const cooperativeMaterials=sqliteTable('cooperative_materials',{cooperativeId:text('cooperative_id').notNull().references(()=>cooperatives.id),material:text('material_type').notNull()},t=>[uniqueIndex('cooperative_material_unique').on(t.cooperativeId,t.material)]);
export const wastePoints=sqliteTable('waste_points',{
 id:text('id').primaryKey(),generatorUserId:text('generator_user_id').notNull().references(()=>users.id),name:text('generator_name').notNull(),type:text('generator_type').notNull(),material:text('material_type').notNull(),kg:real('quantity_kg').notNull(),lat:real('latitude').notNull(),lng:real('longitude').notNull(),address:text('address_private').notNull(),addressPublic:text('address_public').notNull(),street:text('street').notNull().default(''),number:text('number').notNull().default(''),postcode:text('postcode').notNull().default(''),region:text('neighborhood').notNull(),city:text('city').notNull(),state:text('state').notNull(),availability:text('availability').notNull(),availabilityDate:text('availability_date').notNull(),frequency:text('recurrence_type').notNull(),status:text('status',{enum:['available','reserved','scheduled','collected','cancelled']}).notNull().default('available'),reservedBy:text('reserved_by').references(()=>cooperatives.id),scheduledDate:text('scheduled_date'),timeWindow:text('time_window'),scheduleNote:text('schedule_note'),locationConfirmed:integer('location_confirmed',{mode:'boolean'}).notNull().default(true),pickupWindows:text('pickup_windows_json').notNull().default('[]'),accessNote:text('access_note').notNull().default(''),confirmedAt:text('confirmed_at'),expiresAt:text('expires_at'),validityDays:integer('validity_days').notNull().default(7),revision:integer('revision').notNull().default(0),planningReview:integer('planning_review',{mode:'boolean'}).notNull().default(false),legacyKey:text('legacy_key').unique(),...timestamps()
},t=>[index('waste_search_idx').on(t.status,t.material,t.city),index('waste_owner_idx').on(t.generatorUserId),index('waste_reserved_idx').on(t.reservedBy),check('waste_quantity_positive',sql`${t.kg}>0`),check('waste_coordinates_valid',sql`${t.lat} BETWEEN -90 AND 90 AND ${t.lng} BETWEEN -180 AND 180`)]);
export const routes=sqliteTable('routes',{
 id:text('id').primaryKey(),cooperativeId:text('cooperative_id').notNull().references(()=>cooperatives.id),status:text('status',{enum:['draft','scheduled','in_progress','completed','cancelled']}).notNull(),originalDistanceKm:real('original_distance_km'),optimizedDistanceKm:real('optimized_distance_km'),totalWeightKg:real('total_weight_kg').notNull(),comparison:text('comparison_json'),scheduledDate:text('scheduled_date'),timeWindow:text('time_window'),note:text('note'),reviewRequired:integer('review_required',{mode:'boolean'}).notNull().default(false),revision:integer('revision').notNull().default(0),createdAt:text('created_at').notNull(),completedAt:text('completed_at')
},t=>[index('routes_coop_idx').on(t.cooperativeId,t.status)]);
export const routePoints=sqliteTable('route_points',{id:text('id').primaryKey(),routeId:text('route_id').notNull().references(()=>routes.id),wastePointId:text('waste_point_id').notNull().references(()=>wastePoints.id),position:integer('position').notNull(),lat:real('latitude').notNull(),lng:real('longitude').notNull()},t=>[uniqueIndex('route_point_unique').on(t.routeId,t.wastePointId)]);
export const collections=sqliteTable('collections',{
 id:text('id').primaryKey(),cooperativeId:text('cooperative_id').references(()=>cooperatives.id),routeId:text('route_id').unique().references(()=>routes.id),date:text('date').notNull(),status:text('status').notNull(),totalWeightKg:real('total_weight_kg'),totalDistanceKm:real('total_distance_km'),legacyOwnerId:text('legacy_owner_id').references(()=>users.id),createdAt:text('created_at').notNull()
});
export const collectionItems=sqliteTable('collection_items',{id:text('id').primaryKey(),collectionId:text('collection_id').notNull().references(()=>collections.id),wastePointId:text('waste_point_id').notNull().unique().references(()=>wastePoints.id),estimatedWeight:real('estimated_weight').notNull(),actualWeight:real('actual_weight'),collectedAt:text('collected_at').notNull()},t=>[check('actual_weight_positive',sql`${t.actualWeight} IS NULL OR ${t.actualWeight}>0`)]);
export const validationInterviews=sqliteTable('validation_interviews',{id:text('id').primaryKey(),createdBy:text('created_by').notNull().references(()=>users.id),intervieweeType:text('interviewee_type').notNull(),city:text('city').notNull(),mainProblem:text('main_problem').notNull(),currentSolution:text('current_solution').notNull(),difficulty:text('difficulty').notNull(),wouldUse:text('would_use').notNull(),notes:text('notes').notNull(),createdAt:text('created_at').notNull()});
export const auditLogs=sqliteTable('audit_logs',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),action:text('action').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),createdAt:text('created_at').notNull()});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
export const providerCache=sqliteTable('provider_cache',{key:text('key').primaryKey(),payload:text('payload').notNull(),expiresAt:integer('expires_at').notNull()});
export const providerLocks=sqliteTable('provider_locks',{provider:text('provider').primaryKey(),nextAllowed:integer('next_allowed').notNull()});
// A CHECK violation aborts the whole D1 batch if a concurrent operation changed its preconditions.
export const operationGuards=sqliteTable('operation_guards',{id:text('id').primaryKey(),ok:integer('ok').notNull()},t=>[check('operation_precondition',sql`${t.ok}=1`)]);
export const legacyImports=sqliteTable('legacy_imports',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),checksum:text('checksum').notNull(),payload:text('payload_json').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('legacy_import_once').on(t.userId,t.checksum)]);

export type User=typeof users.$inferSelect;
export const accountPlans=sqliteTable('account_plans',{userId:text('user_id').primaryKey().references(()=>users.id),plan:text('plan',{enum:['free','pro','institutional']}).notNull().default('free'),legacy:integer('legacy_access',{mode:'boolean'}).notNull().default(false)},t=>[check('account_plan_valid',sql`${t.plan} IN ('free','pro','institutional')`)]);
export const organizationPlans=sqliteTable('organization_plans',{cooperativeId:text('cooperative_id').primaryKey().references(()=>cooperatives.id),plan:text('plan',{enum:['free','pro','institutional']}).notNull().default('free'),legacy:integer('legacy_access',{mode:'boolean'}).notNull().default(false)},t=>[check('organization_plan_valid',sql`${t.plan} IN ('free','pro','institutional')`)]);
export const accountPreferences=sqliteTable('account_preferences',{userId:text('user_id').primaryKey().references(()=>users.id),theme:text('theme',{enum:['light','dark','system']}).notNull().default('system'),reduceMotion:integer('reduce_motion',{mode:'boolean'}).notNull().default(false),notifications:text('notifications_json').notNull().default('{"scheduling":true,"changes":true,"confirmation":true,"results":true}'),revision:integer('revision').notNull().default(0)},t=>[check('theme_valid',sql`${t.theme} IN ('light','dark','system')`)]);
export const notifications=sqliteTable('notifications',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),type:text('type').notNull(),title:text('title').notNull(),message:text('message').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),readAt:text('read_at'),createdAt:text('created_at').notNull()
},t=>[index('notifications_user_read_idx').on(t.userId,t.readAt,t.createdAt)]);
export type WasteRow=typeof wastePoints.$inferSelect;
export const stopResults=sqliteTable('stop_results',{
 id:text('id').primaryKey(),routeId:text('route_id').references(()=>routes.id),collectionId:text('collection_id').references(()=>collections.id),wastePointId:text('waste_point_id').notNull().references(()=>wastePoints.id),cooperativeId:text('cooperative_id').notNull().references(()=>cooperatives.id),recordedBy:text('recorded_by').notNull().references(()=>users.id),
 pointSnapshot:text('point_snapshot_json'),outcome:text('outcome',{enum:['collected','partial','closed','unavailable','unsuitable','other']}).notNull(),estimatedWeight:real('estimated_weight').notNull(),actualWeight:real('actual_weight').notNull(),remainingKg:real('remaining_kg').notNull().default(0),note:text('note').notNull().default(''),date:text('date').notNull(),createdAt:text('created_at').notNull()
},t=>[uniqueIndex('stop_result_route_point_unique').on(t.routeId,t.wastePointId),index('stop_result_owner_idx').on(t.wastePointId,t.createdAt),check('stop_result_weights',sql`${t.actualWeight}>=0 AND ${t.remainingKg}>=0 AND ((${t.outcome} IN ('collected','partial') AND ${t.actualWeight}>0) OR (${t.outcome} IN ('closed','unavailable','unsuitable','other') AND ${t.actualWeight}=0 AND ${t.remainingKg}=0)) AND (${t.outcome}='partial' OR ${t.remainingKg}=0)`)]);
