'use client';
import {useState,type FormEvent} from 'react';
import {Settings,Save} from 'lucide-react';
import {MATERIALS} from '@/lib/model';
import type {Cooperative,Coordinates,Mode} from '@/types';
import LocationEditor,{blankAddress,type AddressDraft} from '../Map/location-editor';
import {PanelTitle,DataBadge} from '../primitives';
export default function CooperativeSettings({value,mode,onSave,persistent=false}:{value:Cooperative|null|undefined;mode:Mode;onSave:(v:Cooperative)=>void|Promise<void>;persistent?:boolean}){
  const [open,setOpen]=useState(!value),[position,setPosition]=useState<Coordinates|null>(value?{lat:value.lat,lng:value.lng}:null),[confirmed,setConfirmed]=useState(!!value),[accepted,setAccepted]=useState<string[]>(value?.acceptedMaterials??[...MATERIALS]);
  const [address,setAddress]=useState<AddressDraft>({...blankAddress,street:value?.address??'',city:value?.city??'',state:value?.state??''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);if(!position||!confirmed||!accepted.length||!address.street.trim()||(persistent&&(!address.city.trim()||!address.state.trim()))){setError('Informe endereço, cidade e estado, confirme a localização e selecione ao menos um material.');return;}setBusy(true);try{await onSave({id:value?.id??crypto.randomUUID(),name:String(d.get('name')).trim(),address:[address.street,address.number,address.region,address.city,address.state].filter(Boolean).join(', '),...position,city:address.city,state:address.state,radiusKm:Number(d.get('radius')),capacityKg:Number(d.get('capacity')),acceptedMaterials:accepted,source:mode});setError('');setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="panel cooperative-settings"><PanelTitle title={value?value.name:'Configurar cooperativa'} subtitle={value?`${value.radiusKm} km de atuação · ${value.capacityKg} kg por rota`:'Defina a base de partida e sua capacidade de coleta.'} action={<button className="btn light" onClick={()=>setOpen(!open)}><Settings size={16}/>{open?'Recolher':'Configurar'}</button>}/>{open&&<form className="form-body" onSubmit={submit}><div className="form-grid"><label className="wide">Nome da cooperativa<input name="name" maxLength={100} required defaultValue={value?.name}/></label><label>Raio de atuação (km)<input name="radius" type="number" min="1" max="300" step="1" defaultValue={value?.radiusKm??15} required/></label><label>Capacidade estimada (kg por rota)<input name="capacity" type="number" min="1" max="1000000" defaultValue={value?.capacityKg??300} required/></label></div><fieldset className="accepted-materials"><legend>Materiais aceitos</legend>{MATERIALS.map(m=><label className="check-row" key={m}><input type="checkbox" checked={accepted.includes(m)} onChange={()=>setAccepted(a=>a.includes(m)?a.filter(x=>x!==m):[...a,m])}/>{m}</label>)}</fieldset>{value&&<p className="provider-note">Endereço atual: {value.address}. Para alterar a base, complete o endereço e confirme novamente.</p>}<LocationEditor requireAddress={false} address={address} onAddress={setAddress} position={position} onPosition={setPosition} confirmed={confirmed} onConfirmed={setConfirmed}/>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><DataBadge mode={mode}/><button className="btn primary" disabled={busy||!confirmed} type="submit"><Save size={17}/> Salvar cooperativa</button></div></form>}</section>;
}

